### ISSUE TITLE
`ṕ` does not exist as a quick.

### ISSUE THREAD

**Issue by lyxal** [codereport/jello#12]
In this image from the readme:

![](https://i.stack.imgur.com/HUvKY.png)

There's a quick called `prior`, which is translated as `ṕ`. However, there's no `ṕ` documented in the list of quicks, nor is there a `ṕ` character in the codepage. 

By `prior`, did you mean one of the grouping quicks? Those being `¢Çç` for `last link as nilad/moand/dyad`, `$¥` for `last two links as a monad/dyad`, `Ɗɗ` for `last three links as a monad/dyad` and `Ʋʋ` for `last four links as a monad/dyad`.

Other than that, I'm not quite sure what `prior` is supposed to mean. If it's not being converted to something else before executing Jelly, it'll be ignored, making no difference to the way the program is executed.

**Comment by lyxal** [comment]
Also, after reading through `tokens.py`, I noticed there were a few things you marked as `don't know what this does`.

* `Ṿ` is like how python's `repr(x)` returns a string that, when evaluated using `eval`, should return a value the same (if not, close to) `x`. In this case, the string representation is returned as Jelly syntax. [Here's the implementation of how different types are converted](https://github.com/DennisMitchell/jellylanguage/blob/70c9fd93ab009c05dc396f8cc091f72b212fb188/jelly/interpreter.py#L441)
* `Ẏ` flattens a list of nested lists by 1 level; where `F` completely flattens the structure of a list to be 1-dimensional, `Ẏ` "un-nests" each item in a list once. [Try it online!](https://tio.run/##y0rNyan8///hrr7///9HRxvqGOlEG@uY6ERb6FjGxsbqRJvqmMXqmMcCAA "Jelly – Try It Online") - a layer of brackets is removed from each item.
* `G` (`Attempt to format z as a grid`) is a built-in that essentially joins all sublists on spaces and that on newlines. This is mostly for code golf challenges with strict output requirements. The best example I could find from the Code Golf Stack Exchange was [this answer by Dennis](https://codegolf.stackexchange.com/a/77991/78850). Without the `G` at the end, the output is a list of lists ([Try it online!](https://tio.run/##y0rNyan8/79A9VHTGh07wwAgVfz//3/T/2YA "Jelly – Try It Online")), but with the `G`, it's displayed as an evenly spaced grid ([Try it online!](https://tio.run/##y0rNyan8/79A9VHTGh07wwAgVez@//9/0/9mAA "Jelly – Try It Online")). Outside of golf, you can pretty much ignore it.
* `k` is a little hard to explain, but one way to potentially think about it is as so:

`k` takes two arguments: a normal list, and a shape list. The shape list typically consists of 1s and 0s, but you only need to consider the truthiness and falsiness of each value.

The shape list has all consecutive 0s grouped, with the first 1 that follows included in that group. For example:

```
[1,0,0,0,1,1,0,0,1,1]
```

would be grouped as

```
[1, [0,0,0,1], 1, [0,0,1], 1]
```

The normal list is then molded to the shape of the grouped shape list. Now due to internal implementations, if there's a `1` at the end of the shape list, an empty list will be appended to the result. I'm not quite sure why it does that, and if there's one thing rewriting the Jelly regex parser in a regexless way has taught me, it's that Jelly, while good as a language, really could have more code documentation :p. The `partition_at` function is one of those functions that doesn't really tell you why it does things. [It's implementation can be found here](https://github.com/DennisMitchell/jellylanguage/blob/70c9fd93ab009c05dc396f8cc091f72b212fb188/jelly/interpreter.py#L809)

---

Anyhow, that seems to be all the atoms you marked with the `don't understand` comment. Hopefully that helps clarify things if someone hasn't already beaten me to the punch elsewhere.

**Comment by UnrelatedString** [comment]
@lyxal It's defined [in their Jellyfish fork](https://github.com/codereport/jellyfish/blob/49ccc14e8f9b006eb408f910a044fb9b1d52c720/jelly/interpreter.py#L2945); if I'm reading it correctly it appears to be a dyad-only version of `Ɲ`. I would nevertheless recommend not using it to show off something you advertise as a tool for base Jelly.

Also, this is just a personal this-is-bugging-me thing, but would it be too late to rename `R` from `iota` to `range`? `J` corresponds to the conventional APL iota, and it's not like you're using `range` for `r` (for which I might recommend something like `range2` or `..=`).

**Comment by codereport** [comment]
> @lyxal It's defined [in their Jellyfish fork](https://github.com/codereport/jellyfish/blob/49ccc14e8f9b006eb408f910a044fb9b1d52c720/jelly/interpreter.py#L2945); if I'm reading it correctly it appears to be a dyad-only version of `Ɲ`. I would nevertheless recommend not using it to show off something you advertise as a tool for base Jelly.

@lyxal What @UnrelatedString said here ^^ is correct. I have updated the README to say that Jello wraps the Jellyfish executable which is a fork of Jelly. 
 
> Also, this is just a personal this-is-bugging-me thing, but would it be too late to rename `R` from `iota` to `range`? `J` corresponds to the conventional APL iota, and it's not like you're using `range` for `r` (for which I might recommend something like `range2` or `..=`).

I have added overloads for `range` and `range0` (the corresponding names for `iota` and `iota0`)

**Comment by UnrelatedString** [comment]
Oh, and if you're wondering about when `ṾV` isn't quite the identity function, it isn't equipped to handle edge cases that break Jelly's type system like `⁾0Ƭ+/ṾV`.
