### ISSUE TITLE
BUG: 1-2-2 dyadic chain

### ISSUE THREAD

**Issue by tom-huntington** [codereport/jello#14]
I was expecting Φ₁ (or some specialization `fn (f,g,h) = x,y -> g(f(x),h(x,y))`)
```
> 1 2 :: add1 * l
          ‘   × ḷ
   ‘   1 2 ➡️  2
   ‘×  1 2 ➡️  4
   ‘×ḷ 1 2 ➡️  2
    This is a 1-2-2 dyadic chain (ΔΔ)
              └┬┘ ⋮
               Δ  ⋮
               └┬─┘
                Δ
```
Anyway thanks!

**Comment by tom-huntington** [comment]
I guess there are no `2y122` combinators.

You can get around this by explicitly adding a `l`
```
> 1 2 :: l add1 * r
         ḷ  ‘   × ṛ
   ḷ    1 2 ➡️  1
   ḷ‘   1 2 ➡️  2
   ḷ‘×  1 2 ➡️  4
   ḷ‘×ṛ 1 2 ➡️  4
    This is a 2-1-2-2 dyadic chain (B₁Φ₁)
              └┬┘   ⋮
              B₁    ⋮
               └─┬──┘
                Φ₁
```

**Comment by codereport** [comment]
Yea, what you did with the `l` and `r` is probably the best way to do that.

**Comment by codereport** [comment]
Ah I see, ok - I will take a look at this :+1:

**Comment by codereport** [comment]
If we look at the possible 2y122 / 2y221 combinators (which are specializations of Φ₁), we get:
```
g(f(x),h(x,y))  -- Φ.₂
g(f(y),h(x,y))  -- Φ.₄
g(f(x,y),h(x))  -- Φ.₆
g(f(x,y),h(y))  -- Φ.₈
```

So we will call this the `Φ.₂` combinator. I have added it to Jello and now you get:

![image](https://github.com/codereport/jello/assets/36027403/74733fc2-e2d1-460f-ba2c-6cfa612ad65c)
