### ISSUE TITLE
Transpose is spelt zip

### ISSUE THREAD

**Issue by tom-huntington** [codereport/jello#23]
You ended up changing the solution https://github.com/codereport/jello/commit/e61cdcab971189be7a509f020f48e5151bbe22cc

But in you original solution:
```
flip w minr rev = maxr * maxr filter_out 0`   |   z`ṂṚ=Ṁ×Ṁḟ0``
```
You didn't use the most specialized algorithm.

You used dyadic zip `z` (`flip` in jello), when you could have used [monadic zip](https://tio.run/##y0rNyan8/z/q////0dGGOkaxOtHGOiaxsQA) `Z` to transpose the 2d array.

**Comment by codereport** [comment]
Right, should have guessed it borrowed `zip(*___)` from Python. Have renamed Jello's `columns` to `flip` and `flip` to `flip2` https://github.com/codereport/jello/commit/bb6cff6cbee80a44a6d007562bb745833ba821ba. Thanks :pray:
